# Wrangler configuration for Cloudflare Pages
name = "create-js-stack"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "out"

# Build command (optional - can be set in Cloudflare dashboard)
# build = { command = "npm run build" }

# Environment variables (set in Cloudflare dashboard)
# [vars]
# NPM_PACKAGE_NAME = "create-js-stack"
# GITHUB_REPO = "vipinyadav01/js-stack"
